import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import MainProductCollection from '../components/layouts/main/productCollection'
import MainSlideShow from '../components/layouts/main/slideShow'
import MainTopBanner from '../components/layouts/main/topBanner'
import { InferGetStaticPropsType } from 'next'
import { apiProductCategory } from './api'
import axios from 'axios'

interface IProps { }
function Home(props: IProps) {
  console.log('props', props)
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Create Next App</title>
      </Head>
      <div className="main-content">
        <div className="fullwidth-template">
          <MainSlideShow />
          <MainTopBanner />
          <MainProductCollection />
        </div>
      </div>
    </>
  )
}
const https = require("https");
const agent = new https.Agent({
  rejectUnauthorized: false
})

export async function getStaticProps() {
  const menus = await apiProductCategory.getCategory();
  return {
    props: {
      menus,
    },
    revalidate: 10, // In seconds
  }
}

export default Home


