import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { MainSlideShow } from '../components/layouts/main/slideShow'
import { MainTopBanner } from '../components/layouts/main/topBanner'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Create Next App</title>
      </Head>
      <div className="main-content">
        <div className="fullwidth-template">
          {<MainSlideShow />}
          {<MainTopBanner />}
          <div className="cleric-tabs  default rows-space-40">
            <div className="container">
              <div className="tab-head">
                <ul className="tab-link">
                  <li className="active">
                    <a data-toggle="tab" aria-expanded="true" href="#bestseller">Bestseller</a>
                  </li>
                  <li>
                    <a data-toggle="tab" aria-expanded="true" href="#new_arrivals">New Arrivals </a>
                  </li>
                  <li>
                    <a data-toggle="tab" aria-expanded="true" href="#top-rated">Top Rated</a>
                  </li>
                </ul>
              </div>
              <div className="tab-container">
                <div id="bestseller" className="tab-panel active">
                  <div className="cleric-product">
                    <ul className="row list-products auto-clear equal-container product-grid">
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-1.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Super Tweeter</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-2.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Auto Accentss</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-3.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Nardi Bianco</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-4.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Chrimy Lights</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-5.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Series Chrome</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-6.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Shift Knob</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-7.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Vondom Tall</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-8.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">File Cabinet</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
                <div id="new_arrivals" className="tab-panel">
                  <div className="cleric-product">
                    <ul className="row list-products auto-clear equal-container product-grid">
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-9.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Bells Side Table</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-10.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Exotic Diamond</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-11.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Marvellous Ring</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-13.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Dainty Diamond</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-14.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Mausami Ruby Ring</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-15.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">OE Specialty</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-16.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Iridium Spark Plug</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-2.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Ibiza Chair</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
                <div id="top-rated" className="tab-panel">
                  <div className="cleric-product">
                    <ul className="row list-products auto-clear equal-container product-grid">
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-10.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Sport Seats</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-12.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Cross Drilled</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-8.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Big Brake Kit</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-4.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Throttle Bodies</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-9.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Sparta Evolution</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-13.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">Series Slotted</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item product-type-variable col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-16.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#"> Brake Rotors</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="product-item  col-lg-3 col-md-4 col-sm-6 col-xs-6 col-ts-12 style-1">
                        <div className="product-inner equal-element">
                          <div className="product-top">
                            <div className="flash">
                              <span className="onnew">
                                <span className="text">
                                  new
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="product-thumb">
                            <div className="thumb-inner">
                              <a href="#">
                                <img src="assets/images/product-item-8.jpg" alt="img" />
                              </a>
                              <div className="thumb-group">
                                <div className="yith-wcwl-add-to-wishlist">
                                  <div className="yith-wcwl-add-button">
                                    <a href="#">Add to Wishlist</a>
                                  </div>
                                </div>
                                <a href="#" className="button quick-wiew-button">Quick View</a>
                                <div className="loop-form-add-to-cart">
                                  <button className="single_add_to_cart_button button">Add to cart
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-info">
                            <h5 className="product-name product_title">
                              <a href="#">DRL Bar Headlights</a>
                            </h5>
                            <div className="group-info">
                              <div className="stars-rating">
                                <div className="star-rating">
                                  <span className="star-3" />
                                </div>
                                <div className="count-star">
                                  (3)
                                </div>
                              </div>
                              <div className="price">
                                <del>
                                  $65
                                </del>
                                <ins>
                                  $45
                                </ins>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>


          <div className="banner-wrapp rows-space-30">
            <div className="container">
              <div className="row">
                <div className="col-lg-5 col-md-5 col-sm-12">
                  <div className="banner">
                    <div className="item-banner style10">
                      <div className="inner">
                        <div className="banner-content">
                          <h4 className="cleric-subtitle">Jewelry Collection!</h4>
                          <h3 className="title">Big Deal Of The Day</h3>
                          <div className="description">
                            We’ve been waiting for you!
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-7 col-md-7 col-sm-12">
                  <div className="banner">
                    <div className="item-banner style11">
                      <div className="inner">
                        <div className="banner-content">
                          <h4 className="cleric-subtitle">Let’s us make your style!</h4>
                          <h3 className="title">Best Collection </h3>
                          <div className="description">
                            A complete shopping guide on what &amp; how to wear it!
                          </div>
                          <a href="#" className="button btn-shopping-us">Shop now</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Home
